### ISSUE TITLE
Get a crash when Keycloak is used as identity provider.

### ISSUE THREAD

**Issue by bbindra** [hipster-labs/generator-jhipster-entity-audit#102]
When Keycloak is used in Jhipster, the User entity has id field as String, and it fails to log this entity and crashes at 

2019-01-29 14:41:07.654 ERROR 15000 --- [app-Executor-2] i.d.d.c.a.AsyncEntityAuditEventWriter    : Exception while persisting audit entity for User{login='admin', firstName='Admin', lastName='Administrator', email='admin@localhost', imageUrl='null', activated='true', langKey='null'} error: {}

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at io.data.dval.config.audit.AsyncEntityAuditEventWriter.prepareAuditEntity(AsyncEntityAuditEventWriter.java:67)
	at io.data.dval.config.audit.AsyncEntityAuditEventWriter.writeAuditEvent(AsyncEntityAuditEventWriter.java:40)
	at io.data.dval.config.audit.AsyncEntityAuditEventWriter$$FastClassBySpringCGLIB$$ef7cbe27.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

In fact this will be the case for any entity which has id field other than Long/Integer.
The simple fix would be to use String as Id and convert any ID field to string. Let me know if this makes sense.

**Comment by deepu105** [comment]
This was never tested with OIDC, if you find an issue I suggest you provide a PR as I lack time at the moment to look at this

**Comment by DanielFran** [comment]
Closing, since we migrate to a new blueprint version.
If you found any issue with latest version, please open a new issue.
