### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'fields')

### ISSUE THREAD

**Issue by nitram84** [hipster-labs/generator-jhipster-entity-audit#184]
With latest git version and jhipster-generator 7.9.3 I'm getting the following error:

```
Error running generator app: TypeError: Cannot read properties of undefined (reading 'fields')
TypeError: Cannot read properties of undefined (reading 'fields')
    at JavaAuditBlueprint.configureEntity ([..]/generator-jhipster-entity-audit/generators/java-audit/generator.mjs:126:55)
    at Object.<anonymous> ([..]\generator-jhipster-entity-audit\node_modules\yeoman-generator\lib\index.js:1091:23)
    at [..]\generator-jhipster-entity-audit\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at [..]\generator-jhipster-entity-audit\node_modules\run-async\index.js:26:19
    at [..]\generator-jhipster-entity-audit\node_modules\yeoman-generator\lib\index.js:1092:9
    at new Promise (<anonymous>)
    at JavaAuditBlueprint.executeTask ([..]\generator-jhipster-entity-audit\node_modules\yeoman-generator\lib\index.js:1063:12)
    at runLoop.add.once ([..]\generator-jhipster-entity-audit\node_modules\yeoman-generator\lib\index.js:1043:14)
    at Immediate.<anonymous> ([..]\node_modules\grouped-queue\lib\subqueue.js:48:34)
```

I committed a fix here: https://github.com/nitram84/generator-jhipster-entity-audit/commit/706e9d784e66f37a056ab4ce02eb10b012cefd69

**Comment by DanielFran** [comment]
Closed with https://github.com/hipster-labs/generator-jhipster-entity-audit/pull/187
