### ISSUE TITLE
Exception thrown in Post CREATE audit when extending from abstract auditing domain entity 

### ISSUE THREAD

**Issue by sanderpost** [hipster-labs/generator-jhipster-entity-audit#25]
Is this expected behavior due to the following line in the docs?
> The module will extend the selected entities and its DTOs with AbstractAuditingEntity and AbstractAuditingDTO class respectively to enable audits, **hence make sure that your entities/DTOs doesn't have any super class**. 

If it's not, here's what I've done which creates the problem. 
 Pseudo code:
```
@Entity @Inheritance(strategy = InheritanceType.JOINED) abstract class A extends AbstractAuditingEntity { @Id Long Id;}
@Entity class B extends A {}
```
When persisting class B the following execption is thrown:
```
2016-03-22 09:51:40.912 DEBUG 8552 --- [subs-Executor-1] n.b.s.c.a.AsyncEntityAuditEventWriter    : -------------- Post CREATE audit  --------------
2016-03-22 09:51:40.913 ERROR 8552 --- [subs-Executor-1] n.b.s.c.a.AsyncEntityAuditEventWriter    : Exception while getting entity ID and content {}

java.lang.NoSuchFieldException: id
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[na:1.8.0_66-internal]
	at nl.bc.subs.config.audit.AsyncEntityAuditEventWriter.prepareAuditEntity(AsyncEntityAuditEventWriter.java:63) [classes/:na]
	at nl.bc.subs.config.audit.AsyncEntityAuditEventWriter.writeAuditEvent(AsyncEntityAuditEventWriter.java:38) [classes/:na]
	at nl.bc.subs.config.audit.AsyncEntityAuditEventWriter$$FastClassBySpringCGLIB$$e963bdb0.invoke(<generated>) [classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) [spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:108) [spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
```

**Comment by deepu105** [comment]
yes its intended if you find a nice way to handle these kind of cases you can contribute and improve this as well

**Comment by MewesK** [comment]
I've added the following method to AsyncEntityAuditEventWriter and replaced `
            Field privateLongField = entityClass.getDeclaredField("id");` with `
            Field privateLongField = getDeclaredField(entityClass, "id");`

    private static Field getDeclaredField(Class<?> type, String name) throws NoSuchFieldException {
        List<Field> fieldList = new ArrayList<>();
        for (Class<?> c = type; c != null; c = c.getSuperclass()) {
            fieldList.addAll(Arrays.asList(c.getDeclaredFields()));
        }

        fieldList = fieldList.stream().filter(field -> field.getName().equals(name)).collect(Collectors.toList());

        if (fieldList.size() != 1) {
            throw new NoSuchFieldException();
        }

        return fieldList.get(0);
    }`

As soon as I'm sure there are no side effects and after writing some unit tests, I will create a pull request if you are interested.

**Comment by deepu105** [comment]
yes please

**Comment by gwokudasam** [comment]
> private static Field getDeclaredField(Class<?> type, String name) throws NoSuchFieldException {
>     List<Field> fieldList = new ArrayList<>();
>     for (Class<?> c = type; c != null; c = c.getSuperclass()) {
>         fieldList.addAll(Arrays.asList(c.getDeclaredFields()));
>     }
> 
>     fieldList = fieldList.stream().filter(field -> field.getName().equals(name)).collect(Collectors.toList());
> 
>     if (fieldList.size() != 1) {
>         throw new NoSuchFieldException();
>     }
> 
>     return fieldList.get(0);
> }`

This one works well. Thank you
