### ISSUE TITLE
Unable to install/create docker using yo jhipster-docker default

### ISSUE THREAD

**Issue by balakumar1982** [hipster-labs/generator-jhipster-entity-audit#33]
I tried to create micro-services gateway and try to run it via docker. But running below command gives error. 
```
yo jhipster-docker default
module.js:327
    throw err;
    ^

Error: Cannot find module 'generator-jhipster'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Users\balakumar\AppData\Roaming\npm\node_modules\generator-jhipster-docker\generators\app\index.js:6:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)`

```

**Comment by pascalgrimaud** [comment]
You didn't use properly the generator and sub generator.
Plz read http://jhipster.github.io/microservices-architecture/ and http://jhipster.github.io/docker-compose/#3

The correct steps:
1) create gateway and create docker image with : `./mvnw package -Pprod docker:build` or `./gradlew bootRepackage -Pprod buildDocker`
2) create microservices, do same to create docker image
3) create a folder where launching : `yo jhipster:docker-compose` (and not `yo jhipster-docker` as you mentionned)

Last thing: why did you open ticket here? it's the module generator-jhipster-entity-audit... and it's not related to this project.

**Comment by balakumar1982** [comment]
I was googling out for solution and landed over here into this forum. Sorry that I didn't realize that I was marking it at wrong module. Anyways thanks for providing required information.
