### ISSUE TITLE
yo jhipster-entity-audit default fails

### ISSUE THREAD

**Issue by micoud** [hipster-labs/generator-jhipster-entity-audit#65]
Hello,
I tried to run the entity-audit-generator and it failed with this error:

```
TypeError: this.addEntityToCache is not a function
    at Object.addEntityToEhcache (/usr/lib/node_modules/generator-jhipster/generators/generator-base.js:718:14)
    at child.writeBaseFiles (/usr/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:212:24)
    at Object.<anonymous> (/usr/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/lib/base.js:436:25)
    at /usr/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /usr/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /usr/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/lib/base.js:448:8
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```

npm: 3.10.10
node: v6.11.0
yo: 2.0.0
generator-jhipster: v4.5.6
generator-jhipster-entity-audit: v2.4.1

What does this mean? 
The full output is below. 

Thank you in advance.

micoud

--8<--

```
$ yo jhipster-entity-audit
Composing JHipster configuration with module entity-audit
Welcome to the JHipster Entity Audit Generator! v2.4.1

Reading the JHipster project configuration for your module
? Choose which audit framework you would like to use. Custom JHipster auditing (works with SQL)
? Do you want to enable audit for all existing entities? No, let me choose the entities to update
? Please choose the entities to be audited Incident
? Do you want to add an audit log page for entities? Yes
TypeError: this.addEntityToCache is not a function
    at Object.addEntityToEhcache (/usr/lib/node_modules/generator-jhipster/generators/generator-base.js:718:14)
    at child.writeBaseFiles (/usr/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:212:24)
    at Object.<anonymous> (/usr/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/lib/base.js:436:25)
    at /usr/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /usr/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /usr/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/lib/base.js:448:8
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```

**Comment by deepu105** [comment]
Please provide your applications .yo-rc.json and your entity config to reproduce this

**Comment by deepu105** [comment]
This is fixed and released as new version

**Comment by deepu105** [comment]
@micoud please test and let me know

**Comment by micoud** [comment]
@deepu105 I finally found the time to test your new Version (2.5.0) with my project. It works like a charm! Thank you very much for your efforts.
